services:

  server:
    #image: 'nginx:stable-alpine'
    build:
      context: ./dockerfiles/
      dockerfile: nginx.dockerfile
    ports:
      - "58860:80"
    volumes:
      - ./src/:/var/www/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build:
      context: ./dockerfiles/
      dockerfile: php.dockerfile
    volumes:
      - ./src/:/var/www/html/:delegated

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env

  composer:
    build:
      context: ./dockerfiles/
      dockerfile: composer.dockerfile
    volumes:
      - ./src/:/var/www/html/

  #  artisan:

  #  npm:

